# Generated by Django 6.0.1 on 2026-01-17 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.URLField(max_length=255)),
                ('mission_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationReturnInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_on', models.DateField()),
                ('tax_period_start_date', models.DateField()),
                ('tax_period_end_date', models.DateField()),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
