# Generated by Django 6.0.1 on 2026-01-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_datasetjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationreturninformation',
            old_name='total_assets',
            new_name='total_assets_eoy',
        ),
        migrations.AddField(
            model_name='organizationreturninformation',
            name='py_employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationreturninformation',
            name='py_total_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='organizationreturninformation',
            name='py_total_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='organizationreturninformation',
            name='total_assets_boy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='organizationreturninformation',
            name='total_liabilities_boy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='organizationreturninformation',
            name='total_liabilities_eoy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
