# Generated by Django 6.0.1 on 2026-01-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organizationreturninformation_py_total_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationreturninformation',
            name='return_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
