# Generated by Django 6.0.1 on 2026-01-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationreturninformation_return_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationreturninformation',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
